- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  description: "New feature or request"
  color: "a2eeef"

- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"

- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"

- name: "invalid"
  description: "This doesn't seem right"
  color: "e4e669"

- name: "question"
  description: "Further information is requested"
  color: "d876e3"

- name: "wontfix"
  description: "This will not be worked on"
  color: "ffffff"

- name: "icebox"
  description: "icebox or pending"
  color: "c5def5"

- name: "priority::high"
  description: "priorityg high"
  color: "d93f0b"

- name: "priority::low"
  description: "priority low"
  color: "9dcce0"

- name: "priority::medium"
  description: "priority medium"
  color: "fbca04"

- name: "tools"
  description: ""
  color: "510f70"

- name: "C2A"
  description: "Something related with C2A flight software"
  color: "2a9637"

- name: "WINGS"
  description: "Something related with WINGS ground station"
  color: "1503bb"

- name: "automation::comment-graph"
  description: "comment simulation result graph on pull request"
  color: "d4c5f9"

- name: "gui"
  description: "graphical user interface"
  color: "781306"

- name: "test"
  description: "test of the codes"
  color: "25D18F"

- name: "dynamics"
  description: "dynamics calculation"
  color: "F007D6"

- name: "environment"
  description: "environment calculation"
  color: "A917ED"

- name: "disturbance"
  description: "disturbance calculation"
  color: "2B6EA1"

- name: "component"
  description: "component calculation"
  color: "6DF99D"

- name: "library"
  description: "library calculation"
  color: "2275B4"
