name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'ExtLibraries/**'
      - 'CMakeLists.txt'
      - 'src/**'

jobs:
  build_s2e:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: build extlib
        shell: powershell
        working-directory: ExtLibraries
        run: |
          cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_CONFIGURATION_TYPES:STRING="Debug"
          cmake --build .
      - name: install extlib
        shell: powershell
        working-directory: ExtLibraries
        run: |
          cmake --install .
      - name: check extlib
        shell: powershell
        run: |
          ls ..
          ls ../ExtLibraries
          ls ../ExtLibraries/cspice
          ls ../ExtLibraries/cspice/cspice_msvs
          ls ../ExtLibraries/cspice/include
          ls ../ExtLibraries/cspice/generic_kernels
          ls ../ExtLibraries/nrlmsise00
          ls ../ExtLibraries/nrlmsise00/table
          ls ../ExtLibraries/nrlmsise00/lib
          ls ../ExtLibraries/nrlmsise00/lib/libnrlmsise00.lib
          ls ../ExtLibraries/nrlmsise00/src
      - name: build
        shell: cmd
        run: |
          cl.exe
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          cmake -G "Visual Studio 16 2019" -A Win32  -DCMAKE_CONFIGURATION_TYPES:STRING="Debug"
          cmake --build .
