name: Validate scripts

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    paths:
      - '.github/workflows/validate-scripts.yml'
      - 'scripts/**'

jobs:
  validate_script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        script_dir: ['./scripts/Plot']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.1.0
        with:
          python-version: '3.7'

      - name: install pipenv
        run: pip install pipenv

      - name: install Plot script dependencies
        working-directory: ${{ matrix.script_dir }}
        run: |
          pipenv install
          pipenv graph
